<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amazon_nav-bb-button</name>
   <tag></tag>
   <elementGuidId>ff7bba32-12f2-424e-84c1-f5db478623f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.nav-bb-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Go']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>426975a3-a451-4f2b-bc1c-080a55f04c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8b072803-f40e-42c5-83d5-05226288a904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>a24f3701-85f8-4a3f-8014-c3a4bb5683db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>cd1b2ccf-92a1-44ca-a3e6-bf92b3b7e527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-bb-button</value>
      <webElementGuid>0e92aa60-6641-41f2-a224-4f4811d1f200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id1</value>
      <webElementGuid>90767480-2e2c-4ed1-8f4b-dc7be9ad5664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-bb-searchbar&quot;)/form[1]/input[@class=&quot;nav-bb-button&quot;]</value>
      <webElementGuid>065bcb68-21da-434d-b4ac-c97933baf466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Go']</value>
      <webElementGuid>dcda4114-197e-4308-96c5-de0e05496a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-bb-searchbar']/form/input</value>
      <webElementGuid>40fe7481-d194-42ae-8ca0-661137ebe87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>0be3d987-d33b-4eb3-b9cb-dcffa01645ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @title = 'Go']</value>
      <webElementGuid>61353a85-0e41-4e14-a289-4e90b641ed44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
